name: tag build
on:
  push:
    tags: "*"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    uses: deepin-community/.github/.github/workflows/build-tag.yml@release
    secrets:
      BridgeToken: ${{ secrets.BridgeToken }}
